# ------ root_path/dataset_name ------
root_path: 'data'

seed: 3407

# ------ Hyperparamters ------
search_hp: True

search_scale: [10, 7, 1.5]
search_step: [200, 20, 20]

init_beta: 1
init_alpha: 2
init_gamma: 0.1

eps: 0.002
training_feat_num: 800
training_free_feat_num: 700

w_training_free: [0.3, 0.7]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'ucf101'
backbone: 'RN50'

lr: 0.001
augment_epoch: 10
train_epoch: 30
